# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0f02762aa5dd7587c5084bd097b17c89"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "BB Tech Test App"
handle = "bb-tech-test-app"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
